vich_uploader:
  db_driver: orm

  mappings:
    annonces:
      uri_prefix: /assetes/attachment
      upload_destination: "%kernel.project_dir%/public/assetes/attachment"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
